### PR TITLE
Open a file with utf-8

### PR DESCRIPTION
**Pull request by nowamasa**

### CODE REVIEW

**Comment by alexdebrie** [comment]
Deploy preview for *angry-elion-ffa09b* ready!

Built with commit ecd6b631f32a3baa9aa0323c94512885c2173f28

https://deploy-preview-5--angry-elion-ffa09b.netlify.com

**Comment by alexdebrie** [comment]
Thanks for contributing, @nowamasa! Could you make it Python2-friendly, as `open()` doesn't accept an `encoding` argument in Python 2?

**Comment by nowamasa** [comment]
now it should work in Python 2 and 3

**Comment by alexdebrie** [comment]
Thanks, @nowamasa !

**Pull request merged**
