### PR TITLE
Add missing double quote

### PR DESCRIPTION
**Pull request by pjlangley**
Hi Alex. Thanks for your free guide; it really helped me out 👍 In the process, I found a small typo.

### CODE REVIEW

**Comment by alexdebrie** [comment]
Deploy preview for *angry-elion-ffa09b* ready!

Built with commit 6634b474eef7e98dd3c43f747bfbaa7f670079b6

https://deploy-preview-49--angry-elion-ffa09b.netlify.com

**Comment by alexdebrie** [comment]
Thanks, @pjlangley ! Glad it was helpful, and I appreciate you contributing back.

Also, just in case you haven't seen, I'm writing a [DynamoDB book](https://www.dynamodbbook.com/) that's being released tomorrow :).

**Comment by pjlangley** [comment]
> Thanks, @pjlangley ! Glad it was helpful, and I appreciate you contributing back.
> 
> Also, just in case you haven't seen, I'm writing a [DynamoDB book](https://www.dynamodbbook.com/) that's being released tomorrow :).

@alexdebrie You're welcome. Re. your book: Amazing stuff! Well done 👍 I know how much of a slog it is writing a book. I'll keep it in mind going forwards, should I need to step up my DynamoDB game a little more again 🙂

**Comment by alexdebrie** [comment]
Thanks, Peter! :)

**Pull request merged**
